Saimol-Uta/EventosUTA

src/components/ContenedorEvento.astro
src/pages/index.astro

Se construyó el componente para cada evento, el cual consta de una imagen, del título del evento, la duración y su estado. Este componente irá en la sección de eventos.

Se construyó el componente ContenedorEventos.astro Closes #10

---

src/pages/login.astro
src/pages/register.astro

se agrego register a a la seccion pages, con las rutas exactas en la el archivo login, ademas se controlo la edad minima de ingreso al curso

Se agrego la pagina register con un cambio de ruta #16

---

src/components/Navbar.astro

Se construyó un modelo inicial del componente Navbar, sus redirecciones al inicio y a la sección de eventos aún no funcionan porque no están creadas las páginas a las que se va a dirigir.

Se construyó el componente Navbar Closes #2

---

src/components/filtros.astro

Se realizo los filtros por categorías que despliega las categorías existentes, además los cursos para las carreras de la facultado y la duración del mismo.

Se realizo los filtros por categorías, carreras y duración  #4

---

public/js/buscador.js
src/components/ContenedorEvento.astro
src/components/EventoCard.astro
src/pages/cursosCompleto.astro

Se creo la pagina de los cursos completos además se agrego funcionalidad al botón para que funcione buscar cursos, se modifico un poco el componenteContenedorEvento

Se agrego la pagina de todos los cursos #21

---

src/pages/Descri.astro

La Pagina esta hecha de descri y la Agregacion de componentes de mi compañera Carol Cañizares, a la pagina Descri

Agregacion de componentes y pagina Descripcion Closes #20

---

src/components/Header.astro
src/pages/buscarCertificado.astro
src/pages/login.astro

Se creo la página buscarCertificados y se añadieron los vínculos a home en el botón regresar tanto en buscarCertificados como en el login, además se añadió la referencia a la pagina buscarCertificados desde el Header.

Se agregó la página para buscar certificados Closes #22

---

src/components/Footer.astro

Se agrego el componente footer para poderlo usar en las paginas que se requiera

Se creo el componente Footer.astro #32

---

src/components/ContenedorInfo.astro
src/components/InformacionFacultad.astro
src/pages/index.astro

Se cambió el diseño del componente ContenedorInfo.astro, se creó un componente para almacenar la información de la facultad llamado InformacionFacultad.astro que utiliza al ContenedorInfo.astro para almacenar la misión, visión y descripción general.

Arreglo del Componente ContenedorInfo.astro Closes #31

---

src/components/ContenedorEvento.astro
src/components/InformacionFacultad.astro
src/components/Navbar.astro
src/pages/Descri.astro
src/pages/buscarCertificado.astro
src/pages/index.astro
src/pages/login.astro

- Moderniza la presentación y diseño de los componentes principales, como el contenedor de eventos, información y navegación, para una experiencia más atractiva y coherente.
- Introduce componentes reutilizables para el formulario de inscripción y la sección informativa de la facultad, facilitando futuras modificaciones y mantenimiento.
- Sustituye imágenes locales por enlaces externos optimizados en los cursos, mejorando la calidad visual.
- Añade un footer profesional y una página dedicada para la búsqueda de certificados, enriqueciendo la oferta informativa y la navegabilidad.
- Ajusta el flujo de navegación y la distribución de los elementos para mayor comodidad del usuario en diferentes dispositivos.
Mejora la cohesión visual y la facilidad de edición, preparando la aplicación para …

Mejora la estructura visual y funcional de la landing

---

src/components/ComponenteMenuConfiguraciones.astro

Se construyó un componente de tipo menú desplegable en el que los usuarios que ya iniciaron sesión podrán escoger entre sus opciones entre las cuales se encuentran: ver perfil, ver eventos y cerrar sesión.

Implementar el  componente para el Menú de los usuarios Closes #47

---

src/components/ComponenteMenuConfiguraciones.astro
src/components/HeaderUsuario.astro

Se implementó un componente header igual que el original que implementa el componente de tipo menú desplegable, que aparece una vez que el usuario ha iniciado sesión exitosamente.

Implementar el componente Header para los usuarios autenticados una vez que iniciaron sesión Closes #50

---

src/components/MenuAdministrador.astro

Se implementó una barra de navegación que aparece solo cuando un usuario de tipo administrador se registra.

Implementación  del componente MenuAdministrador.astro

---

src/components/InformacionUsuario.astro
src/pages/CompletarPerfilUser.astro

Se utilizó los componentes creados(InformacionUsuarioItem e InformacionUsuario) con los que se creo contenedores, y se implementaron en la page: CompletarPerfilUser.astro, donde se realizo la Validación progresiva de formularios, que se muestra el formulario con su respetiva accion en caso la cedula ingresada  existao no

Interfaz de la página CompletarPerfilUser Closes #57

---

src/actions/Users/getUserByCedula.action.ts
src/actions/Users/getUsers.ts
src/actions/Users/index.ts
src/actions/Users/setUsers.action.ts
src/actions/index.ts
src/components/InformacionUsuario.astro
src/components/InformacionUsuarioItem.astro
src/pages/CompletarPerfilUser.astro

Se integro la funcionalidad para la pagina del usuario puede traer de la base de datos su informacion y si no hay lo puede crear ahi mismo

Feature/funcionalidadUsuario Closes #58

---

prisma/schema.prisma
src/components/Avatar.astro
src/components/DocumentButton.astro
src/components/EventoUsuario.astro
src/components/HeaderUsuario.astro
src/pages/homeAdmin.astro
src/pages/homeUser.astro

Se puso a funcionar la lógica para el historial de eventos del usuario, se realizaron cambios en el header del usuario y a las páginas homeUser y homeAdmin para que muestren los nombres del usuario registrado tanto en el menú desplegable como debajo de la imagen de avatar, asimismo se proporcionó una funcionalidad inicial a la imagen del avatar y a los botones para subir documentos para que se pueden subir archivos e imágenes.

Arreglar las páginas de inicio del usuario y del administrador Closes #71

---

src/components/ContenedorEvento.astro
src/components/RenderPageNum.astro
src/pages/Formularios/FormularioSolicitudCambioUsuario.astro
src/pages/cursosCompleto.astro

Se mejoro la vista de los cursos con paginación, y también se arreglo el formulario de cambios

Feature/paginacionCursos Closes #68

---

package-lock.json
package.json
prisma/schema.prisma
src/actions/Users/getCuentaById.action.ts
src/actions/Users/index.ts
src/actions/Users/uploadDocumentImage.action.ts
src/actions/Users/uploadImgeUser.action.ts
src/actions/index.ts
src/components/Avatar.astro
src/components/DocumentButton.astro
src/components/Header.astro
src/middleware.ts
src/pages/Admin/EventosCRUD.astro
src/pages/homeAdmin.astro
src/pages/homeUser.astro
src/utils/image-upload.ts

- Incorpora la capacidad para que usuarios y administradores suban imágenes de perfil y documentos personales (cédula, matrícula, extensión), integrando la gestión de archivos con Cloudinary y asegurando la eliminación de imágenes anteriores.
- Actualiza componentes de perfil para mostrar y actualizar imágenes en tiempo real, ajusta lógica de validación y carga, y refuerza la consistencia de datos en la cuenta del usuario.
- **Integración Cloudinary**: Utiliza Cloudinary para almacenar imágenes de usuario y documentos, con validación de tamaño (hasta 5MB) y tipo de archivo permitido (jpg, png, webp).
- **Eliminación segura de imágenes previas**: Al subir una nueva imagen, elimina la anterior asociada en Cloudinary para optimizar almacenamiento y mantener coherencia.
- **Acciones y …

Añade carga de imágenes de documentos y de usuario con integración a Cloudinary

---

src/actions/Carreras/crear-carrera.action.ts
src/actions/Carreras/eliminar-carrera.action.ts
src/actions/Carreras/get-carreras.action.ts
src/actions/Carreras/index.ts
src/actions/Carreras/modificar-carrera.action.ts
src/actions/Inscripcion/get-by-id-inscripciones.action.ts
src/actions/Inscripcion/get-evento.action.ts
src/actions/Inscripcion/index.ts
src/actions/Inscripcion/update-estado-inscripcion.action.ts
src/actions/Inscripcion/update-participante.action.ts
src/actions/index.ts
src/components/ModalDetallesCarrera.astro
src/components/ModalDetallesInscripcion.astro
src/components/ModalDetallesPago.astro
src/pages/Admin/AprobacionInscripciones.astro
src/pages/Admin/CarrerasCRUD.astro
src/pages/Admin/EventosCRUD.astro
src/pages/gestionEventos.astro
src/pages/inscripciones/[eventoId].astro
src/pages/participantes/[eventoId].astro

Implementa la lógica y el diseño necesarios para que administradores puedan revisar, aprobar y calificar inscripciones de usuarios a eventos.
- Añade acciones para obtener inscripciones por evento, actualizar el estado de inscripción (aprobación/rechazo) y registrar calificaciones y asistencias.
- Proporciona componentes y modales reutilizables que facilitan la visualización y gestión de inscripciones pendientes, documentos y pagos.
- Mejora la experiencia de usuario para administradores con interfaces dedicadas para la administración de participaciones.
- Permite flujos completos de revisión, desde la documentación hasta el registro de notas y asistencia.
- Centraliza y automatiza el proceso de gestión de inscripciones.
- Facilita la toma de decisiones por parte del administrador con …

Desarrolla gestión completa de inscripciones para admins Y CRUDS

---

src/components/Admin/CategoriasCRUD/ModalModificarCategoria.astro
src/components/Admin/CategoriasCRUD/ModalNuevaCategoria.astro
src/pages/Admin/Asignaciones.astro
src/pages/Admin/CategoriasCRUD.astro

Se implementaron las diseños requeridos.

Se crearon los diseños para el proceso CRUD de categorías

---

src/components/Admin/UsuariosCRUD/ModalDetallesCuenta.astro
src/components/Admin/UsuariosCRUD/ModalDetallesUsuario.astro
src/components/Admin/UsuariosCRUD/ModalGestionarCuenta.astro
src/components/Admin/UsuariosCRUD/ModalModificarUsuario.astro
src/components/Admin/UsuariosCRUD/ModalNuevoUsuario.astro
src/pages/Admin/UsuariosCRUD.astro
src/styles/Admin/ModalGestionarCuenta.css

Se implementaron diseños para:
- Página principal de CRUD
- Modal para mostrar los detalles de Usuarios
- Modal para mostrar los datos de Cuentas
- Modal para modificar los datos de Usuarios
- Modal para modificar los datos de Cuentas
- Modal para crear nuevos  Usuarios

Se crearon los diseños para el CRUD de Usuarios/Cuentas

---

src/actions/Admin/eliminarOrganizador.action.ts
src/actions/Admin/getOrganizadores.action.ts
src/actions/Admin/index.ts
src/actions/Admin/setOrganizadores.action.ts
src/actions/Admin/updateOrganizadores.action.ts
src/actions/index.ts
src/components/Admin/OrganizadoresCRUD/ModalDetallesOrganizador.astro
src/components/Admin/OrganizadoresCRUD/ModalModificarOrganizador.astro
src/components/Admin/OrganizadoresCRUD/ModalNuevoOrganizador.astro
src/pages/Admin/OrganizadoresCRUD.astro

Se realiza el back trayendo de la base de datos todos los elementos  de organizador y poderlos editar, eliminar . no permite eliminar si esta con eventos asociados

Feature/grud organizadores Closes #111

---

src/pages/Admin/AprobacionInscripciones.astro
src/pages/participantes/[eventoId].astro
src/styles/AprobacionesInscripciones.css

Se realizaron correcciones relacionados con estiilos en las páginas de inscripción y participación

Se corrigieron estilos menores

---

src/components/ContenedorInfo.astro
src/components/Footer.astro
src/components/MenuAdministrador.astro
src/components/Navbar.astro
src/pages/Admin/AprobacionInscripciones.astro
src/pages/Admin/Asignaciones.astro
src/pages/Admin/CarrerasCRUD.astro
src/pages/Admin/CategoriasCRUD.astro
src/pages/Admin/EventosCRUD.astro
src/pages/Admin/OrganizadoresCRUD.astro
src/pages/Admin/UsuariosCRUD.astro
src/pages/Admin/gestionEventos.astro
src/pages/index.astro

Se realizaron mejoras en los estilos y navegacion del proyecto

Se realización diversas correciones de estilos  Closes #119

---

auth.config.ts
prisma/schema.prisma
src/actions/Users/get-cuenta-byID-single.action.ts
src/actions/Users/get-users-with-accounts.action.ts
src/actions/Users/getCuentaById.action.ts
src/actions/Users/modificar-cuenta.action.ts
src/actions/auth/get-user-by-id.action.ts
src/actions/auth/registerUser.action.ts
src/interface/prismaModels.ts

- Refactoriza el modelo de datos principal fusionando las entidades de usuario y cuenta, consolidando la autenticación, la información de usuario y las relaciones en una única tabla de usuarios.
- Actualiza toda la lógica, las acciones y las consultas relacionadas para usar la nueva estructura unificada, eliminando las dependencias de la antigua tabla de cuentas.
- Mejora los procesos de registro, modificación y autenticación de usuarios para una mayor facilidad de mantenimiento y claridad.
- Mejora la autorización y el registro de intentos de inicio de sesión, la validación de contraseñas y la búsqueda de usuarios.
- Limpia y actualiza el esquema de Prisma y las interfaces de TypeScript para alinearse con el nuevo modelo, simplificando el código relacionado y mejorando la seguridad de …

Refactoriza la estructura de usuarios y cuentas, actualiza la lógica relacionada

---

src/actions/auth/registerUser.action.ts
src/pages/register.astro

Se implemento el contro de contraseñas especificado.

Feature/eu 48 control contraseña

---

src/components/EventoCard.astro
src/pages/cursosCompleto.astro

Se realizo a falta dle diseño d ela logica de las tarjetas (6 por pagina) que obtengan las horas, estaod y precio

Feature/eu 5 Diseño de tarjetas

---

src/actions/Eventos/getCertificados.ts
src/actions/Users/get-cuenta-byID-single.action.ts
src/components/TarjetaEvento.astro
src/pages/User/certificadosUsuario.astro
src/pages/User/historial.astro
src/pages/homeUser.astro

Se mejoro la lógica de generar el certificado , para que respecte dinamicamente todo sobre un evento

Feature/eu 38 control certificado 
